AllCops:
  TargetRubyVersion: 2.2
Layout/IndentHeredoc:
  Enabled: false
#here is one more check
# not a bad notion except when you are actually trying to select things that are not(something)
Style/InverseMethods:
  Enabled: false
